version: "3.7"

services:
  docker_proxy:
    container_name: docker_proxy
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "80:80"
      - "8090:8090"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/go/src/github.com/pexni/docker-gateway:/app
    command:
      - /app/main.go
    restart: always


